-- MySQL Script generated by MySQL Workbench
-- 02/24/16 02:04:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WMS` ;

-- -----------------------------------------------------
-- Schema WMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WMS` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `WMS` ;

-- -----------------------------------------------------
-- Table `ToaXe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ToaXe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ToaXe` (
  `idToaXe` INT NOT NULL,
  `tChungLoai` VARCHAR(45) NOT NULL,
  `NamCheTao` YEAR NOT NULL,
  `TrangThaiToa` VARCHAR(20) NOT NULL,
  `NgayDen` DATE NULL,
  `NgayDuKienRa` DATE NULL,
  `NgayRaThucTe` DATE NULL,
  PRIMARY KEY (`idToaXe`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GaTau`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GaTau` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `GaTau` (
  `idGaTau` INT NOT NULL,
  `TenGa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGaTau`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ChungLoaiToa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChungLoaiToa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ChungLoaiToa` (
  `idChungLoaiToa` INT NOT NULL,
  `TenLoaiToa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChungLoaiToa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DonViSuaChua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DonViSuaChua` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DonViSuaChua` (
  `idDonViSuaChua` INT NOT NULL,
  `TenDVSC` VARCHAR(45) NOT NULL,
  `SoDienThoaiDVSC` VARCHAR(45) NOT NULL,
  `DiaChiDVSC` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDonViSuaChua`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `NgayBaoDuong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NgayBaoDuong` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `NgayBaoDuong` (
  `idToaXe` INT NOT NULL,
  `NgayBatDauChay` DATE not NULL,
  `NgayDuKienSua` DATE not NULL,
  `SoNgayBaoDuong` INT not NULL,
  PRIMARY KEY (`idToaXe`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LoaiHangHoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LoaiHangHoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LoaiHangHoa` (
  `idLoaiHangHoa` INT NOT NULL,
  `TenLoaiHang` VARCHAR(45) NOT NULL,
  `Gia` FLOAT NOT NULL,
  PRIMARY KEY (`idLoaiHangHoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `User` (`username` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `User` (`email` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
