-- MySQL Script generated by MySQL Workbench
-- 03/02/16 00:08:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`wagon_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wagon_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wagon_status` (
  `status_id` INT NOT NULL,
  `name_of_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`station` ;

CREATE TABLE IF NOT EXISTS `mydb`.`station` (
  `station_id` INT NOT NULL,
  `station_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kind_of_wagon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kind_of_wagon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kind_of_wagon` (
  `kind_id` INT NOT NULL,
  `kind_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`kind_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wagon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wagon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wagon` (
  `wagon_id` INT NOT NULL,
  `wagon_number` INT NOT NULL,
  `created_year` YEAR NOT NULL,
  `start_date` DATETIME NOT NULL,
  `wagon_status_id_status` INT NOT NULL,
  `station_station_id` INT NOT NULL,
  `kind_of_wagon_kind_id` INT NOT NULL,
  PRIMARY KEY (`wagon_id`),
  INDEX `fk_wagon_wagon_status_idx` (`wagon_status_id_status` ASC),
  INDEX `fk_wagon_station1_idx` (`station_station_id` ASC),
  INDEX `fk_wagon_kind_of_wagon1_idx` (`kind_of_wagon_kind_id` ASC),
  CONSTRAINT `fk_wagon_wagon_status`
    FOREIGN KEY (`wagon_status_id_status`)
    REFERENCES `mydb`.`wagon_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_station`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `mydb`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_kind_of_wagon1`
    FOREIGN KEY (`kind_of_wagon_kind_id`)
    REFERENCES `mydb`.`kind_of_wagon` (`kind_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand_repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand_repair` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand_repair` (
  `brand_repair_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`brand_repair_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`date_repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`date_repair` ;

CREATE TABLE IF NOT EXISTS `mydb`.`date_repair` (
  `id_date_repair` INT NOT NULL,
  `begin_day` DATETIME NOT NULL,
  `repair_day` DATETIME NOT NULL,
  `repair_complete_day` DATETIME NOT NULL,
  `no_days_warning` INT NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  `brand_repair_brand_repair_id` INT NOT NULL,
  PRIMARY KEY (`id_date_repair`),
  INDEX `fk_date_repair_wagon1_idx` (`wagon_wagon_id` ASC),
  INDEX `fk_date_repair_brand_repair1_idx` (`brand_repair_brand_repair_id` ASC),
  CONSTRAINT `fk_date_repair_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `mydb`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_date_repair_brand_repair1`
    FOREIGN KEY (`brand_repair_brand_repair_id`)
    REFERENCES `mydb`.`brand_repair` (`brand_repair_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wagon_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wagon_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wagon_history` (
  `wagon_history_id` INT NOT NULL,
  `cur_time` TIMESTAMP NOT NULL,
  `station_station_id` INT NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  `wagon_status_status_id` INT NOT NULL,
  PRIMARY KEY (`wagon_history_id`),
  INDEX `fk_wagon_history_station1_idx` (`station_station_id` ASC),
  INDEX `fk_wagon_history_wagon1_idx` (`wagon_wagon_id` ASC),
  INDEX `fk_wagon_history_wagon_status1_idx` (`wagon_status_status_id` ASC),
  CONSTRAINT `fk_wagon_history_station1`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `mydb`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_history_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `mydb`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_history_wagon_status1`
    FOREIGN KEY (`wagon_status_status_id`)
    REFERENCES `mydb`.`wagon_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customer_id` INT NOT NULL,
  `cust_name` VARCHAR(45) NOT NULL,
  `cust_telephone` INT NOT NULL,
  `cust_address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kind_of_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kind_of_goods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kind_of_goods` (
  `kind_of_goods_id` INT NOT NULL,
  `kind_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kind_of_goods_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shipping_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`shipping_cost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`shipping_cost` (
  `shipping_cost_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  `kind_of_goods_kind_of_goods_id` INT NOT NULL,
  PRIMARY KEY (`shipping_cost_id`),
  INDEX `fk_shipping_cost_kind_of_goods1_idx` (`kind_of_goods_kind_of_goods_id` ASC),
  CONSTRAINT `fk_shipping_cost_kind_of_goods1`
    FOREIGN KEY (`kind_of_goods_kind_of_goods_id`)
    REFERENCES `mydb`.`kind_of_goods` (`kind_of_goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contract` (
  `contract_id` INT NOT NULL,
  `number_of_contract` INT NOT NULL,
  `customer_customer_id` INT NOT NULL,
  `shipping_cost_shipping_cost_id` INT NOT NULL,
  `kind_of_goods_kind_of_goods_id` INT NOT NULL,
  `station_station_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_customer1_idx` (`customer_customer_id` ASC),
  INDEX `fk_contract_shipping_cost1_idx` (`shipping_cost_shipping_cost_id` ASC),
  INDEX `fk_contract_kind_of_goods1_idx` (`kind_of_goods_kind_of_goods_id` ASC),
  INDEX `fk_contract_station1_idx` (`station_station_id` ASC),
  CONSTRAINT `fk_contract_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `mydb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_shipping_cost1`
    FOREIGN KEY (`shipping_cost_shipping_cost_id`)
    REFERENCES `mydb`.`shipping_cost` (`shipping_cost_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_kind_of_goods1`
    FOREIGN KEY (`kind_of_goods_kind_of_goods_id`)
    REFERENCES `mydb`.`kind_of_goods` (`kind_of_goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_station1`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `mydb`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lading_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lading_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lading_status` (
  `lading_status_id` INT NOT NULL,
  `name_of_status_lading` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lading_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lading` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lading` (
  `lading_id` INT NOT NULL,
  `created_time` TIMESTAMP NULL,
  `lading_status_lading_status_id` INT NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  PRIMARY KEY (`lading_id`),
  INDEX `fk_lading_lading_status1_idx` (`lading_status_lading_status_id` ASC),
  INDEX `fk_lading_wagon1_idx` (`wagon_wagon_id` ASC),
  CONSTRAINT `fk_lading_lading_status1`
    FOREIGN KEY (`lading_status_lading_status_id`)
    REFERENCES `mydb`.`lading_status` (`lading_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lading_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `mydb`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
