-- MySQL Script generated by MySQL Workbench
-- 03/15/16 23:20:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WMS` ;

-- -----------------------------------------------------
-- Schema WMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WMS` DEFAULT CHARACTER SET utf8 ;
USE `WMS` ;

-- -----------------------------------------------------
-- Table `WMS`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`station` ;

CREATE TABLE IF NOT EXISTS `WMS`.`station` (
  `station_id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  `station_values` DOUBLE NOT NULL,
  PRIMARY KEY (`station_id`),
  UNIQUE INDEX `station_name_UNIQUE` (`station_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`kind_of_wagon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`kind_of_wagon` ;

CREATE TABLE IF NOT EXISTS `WMS`.`kind_of_wagon` (
  `kind_id` INT NOT NULL AUTO_INCREMENT,
  `kind_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`kind_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`wagon_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`wagon_status` ;

CREATE TABLE IF NOT EXISTS `WMS`.`wagon_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `name_of_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_id_UNIQUE` (`status_id` ASC),
  UNIQUE INDEX `name_of_status_UNIQUE` (`name_of_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`wagon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`wagon` ;

CREATE TABLE IF NOT EXISTS `WMS`.`wagon` (
  `wagon_id` INT NOT NULL AUTO_INCREMENT,
  `wagon_number` INT NOT NULL,
  `created_year` YEAR NOT NULL,
  `start_date` DATETIME NOT NULL,
  `station_station_id` INT NOT NULL,
  `kind_of_wagon_kind_id` INT NOT NULL,
  `wagon_status_status_id` INT NOT NULL,
  PRIMARY KEY (`wagon_id`),
  INDEX `fk_wagon_station1_idx` (`station_station_id` ASC),
  INDEX `fk_wagon_kind_of_wagon1_idx` (`kind_of_wagon_kind_id` ASC),
  UNIQUE INDEX `wagon_id_UNIQUE` (`wagon_id` ASC),
  UNIQUE INDEX `wagon_number_UNIQUE` (`wagon_number` ASC),
  INDEX `fk_wagon_wagon_status1_idx` (`wagon_status_status_id` ASC),
  CONSTRAINT `fk_wagon_station`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `WMS`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_kind_of_wagon1`
    FOREIGN KEY (`kind_of_wagon_kind_id`)
    REFERENCES `WMS`.`kind_of_wagon` (`kind_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wagon_wagon_status1`
    FOREIGN KEY (`wagon_status_status_id`)
    REFERENCES `WMS`.`wagon_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`brand_repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`brand_repair` ;

CREATE TABLE IF NOT EXISTS `WMS`.`brand_repair` (
  `brand_repair_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`brand_repair_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`date_repair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`date_repair` ;

CREATE TABLE IF NOT EXISTS `WMS`.`date_repair` (
  `id_date_repair` INT NOT NULL AUTO_INCREMENT,
  `begin_day` DATETIME NOT NULL,
  `repair_day` DATETIME NOT NULL,
  `repair_complete_day` DATETIME NOT NULL,
  `no_days_warning` INT NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  `brand_repair_brand_repair_id` INT NOT NULL,
  PRIMARY KEY (`id_date_repair`),
  INDEX `fk_date_repair_wagon1_idx` (`wagon_wagon_id` ASC),
  INDEX `fk_date_repair_brand_repair1_idx` (`brand_repair_brand_repair_id` ASC),
  CONSTRAINT `fk_date_repair_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `WMS`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_date_repair_brand_repair1`
    FOREIGN KEY (`brand_repair_brand_repair_id`)
    REFERENCES `WMS`.`brand_repair` (`brand_repair_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`wagon_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`wagon_history` ;

CREATE TABLE IF NOT EXISTS `WMS`.`wagon_history` (
  `wagon_history_id` INT NOT NULL AUTO_INCREMENT,
  `cur_time` TIMESTAMP NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  PRIMARY KEY (`wagon_history_id`),
  INDEX `fk_wagon_history_wagon1_idx` (`wagon_wagon_id` ASC),
  CONSTRAINT `fk_wagon_history_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `WMS`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`customer` ;

CREATE TABLE IF NOT EXISTS `WMS`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(45) NOT NULL,
  `cust_telephone` INT NOT NULL,
  `cust_address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`contract` ;

CREATE TABLE IF NOT EXISTS `WMS`.`contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `number_of_contract` INT NOT NULL,
  `customer_customer_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_customer1_idx` (`customer_customer_id` ASC),
  UNIQUE INDEX `number_of_contract_UNIQUE` (`number_of_contract` ASC),
  CONSTRAINT `fk_contract_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `WMS`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`kind_of_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`kind_of_goods` ;

CREATE TABLE IF NOT EXISTS `WMS`.`kind_of_goods` (
  `kind_of_goods_id` INT NOT NULL AUTO_INCREMENT,
  `kind_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kind_of_goods_id`),
  UNIQUE INDEX `kind_name_UNIQUE` (`kind_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`unit_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`unit_price` ;

CREATE TABLE IF NOT EXISTS `WMS`.`unit_price` (
  `unit_price_id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  `kind_of_goods_kind_of_goods_id` INT NOT NULL,
  PRIMARY KEY (`unit_price_id`),
  INDEX `fk_shipping_cost_kind_of_goods1_idx` (`kind_of_goods_kind_of_goods_id` ASC),
  CONSTRAINT `fk_shipping_cost_kind_of_goods1`
    FOREIGN KEY (`kind_of_goods_kind_of_goods_id`)
    REFERENCES `WMS`.`kind_of_goods` (`kind_of_goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`lading_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`lading_status` ;

CREATE TABLE IF NOT EXISTS `WMS`.`lading_status` (
  `lading_status_id` INT NOT NULL AUTO_INCREMENT,
  `name_of_status_lading` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lading_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`contract_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`contract_detail` ;

CREATE TABLE IF NOT EXISTS `WMS`.`contract_detail` (
  `contract_detail_id` INT NOT NULL AUTO_INCREMENT,
  `kind_of_goods_kind_of_goods_id` INT NOT NULL,
  `unit_price_unit_price_id` INT NOT NULL,
  `contract_contract_id` INT NOT NULL,
  `station_station_id` INT NOT NULL,
  `weight_of_goods` FLOAT NOT NULL,
  PRIMARY KEY (`contract_detail_id`),
  INDEX `fk_contract_detail_kind_of_goods1_idx` (`kind_of_goods_kind_of_goods_id` ASC),
  INDEX `fk_contract_detail_unit_price1_idx` (`unit_price_unit_price_id` ASC),
  INDEX `fk_contract_detail_contract1_idx` (`contract_contract_id` ASC),
  INDEX `fk_contract_detail_station1_idx` (`station_station_id` ASC),
  CONSTRAINT `fk_contract_detail_kind_of_goods1`
    FOREIGN KEY (`kind_of_goods_kind_of_goods_id`)
    REFERENCES `WMS`.`kind_of_goods` (`kind_of_goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_detail_unit_price1`
    FOREIGN KEY (`unit_price_unit_price_id`)
    REFERENCES `WMS`.`unit_price` (`unit_price_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_detail_contract1`
    FOREIGN KEY (`contract_contract_id`)
    REFERENCES `WMS`.`contract` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_detail_station1`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `WMS`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMS`.`lading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMS`.`lading` ;

CREATE TABLE IF NOT EXISTS `WMS`.`lading` (
  `lading_id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL,
  `lading_status_lading_status_id` INT NOT NULL,
  `wagon_wagon_id` INT NOT NULL,
  `contract_contract_id` INT NOT NULL,
  `total_price` DOUBLE NULL,
  `contract_detail_contract_detail_id` INT NOT NULL,
  PRIMARY KEY (`lading_id`),
  INDEX `fk_lading_lading_status1_idx` (`lading_status_lading_status_id` ASC),
  INDEX `fk_lading_wagon1_idx` (`wagon_wagon_id` ASC),
  INDEX `fk_lading_contract1_idx` (`contract_contract_id` ASC),
  INDEX `fk_lading_contract_detail1_idx` (`contract_detail_contract_detail_id` ASC),
  CONSTRAINT `fk_lading_lading_status1`
    FOREIGN KEY (`lading_status_lading_status_id`)
    REFERENCES `WMS`.`lading_status` (`lading_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lading_wagon1`
    FOREIGN KEY (`wagon_wagon_id`)
    REFERENCES `WMS`.`wagon` (`wagon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lading_contract1`
    FOREIGN KEY (`contract_contract_id`)
    REFERENCES `WMS`.`contract` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lading_contract_detail1`
    FOREIGN KEY (`contract_detail_contract_detail_id`)
    REFERENCES `WMS`.`contract_detail` (`contract_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
